name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile Java projects
        run: |
          mvn clean install -f Data-Entry/pom.xml
          mvn clean install -f Authentication/pom.xml
          mvn clean install -f Analytics/pom.xml
          mvn clean install -f ShowData/pom.xml

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push data-entry-app image
        uses: docker/build-push-action@v5
        with:
          context: ./Data-Entry
          file: ./Data-Entry/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/data-entry:latest

      - name: Build and push authentication-service image
        uses: docker/build-push-action@v5
        with:
          context: ./Authentication
          file: ./Authentication/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-authentication:latest

      - name: Build and push analytics-service image
        uses: docker/build-push-action@v5
        with:
          context: ./Analytics
          file: ./Analytics/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-analytics:latest

      - name: Build and push show-results-app image
        uses: docker/build-push-action@v5
        with:
          context: ./ShowData
          file: ./ShowData/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/showdata:latest